version: '2'
services:
  jenkins:
    image: 'docker.io/bitnami/jenkins:2-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_data:
    driver: local